---
title: "GPIM 452: Group 1 Main Analysis"
format: html
editor: visual
---

## Preliminary logistics

```{r message = FALSE}
# loading packages
library(haven)
library(tidyverse)
library(readxl)
library(here)
library(janitor)
library(zipcodeR)

# for randomization
set.seed(0000)
```

## LAT Raw data loading

```{r}
LAT = read_excel(here("Data Raw", "Labor action tracker data 12.4.23.xlsx"))

LAT

```

## Merging the ACS datasets

```{r}
acs_merged = read.csv(here("Data Raw", "acs_merged.csv"))
LE = read_csv("###.csv")
MC = read_csv("###.csv")
CW = read_csv("###.csv")

# trimming white spaces
LE$state <- trimws(acs$state)
MC$state <- trimws(MC$state)
CW$state <- trimws(CW$state)

# merge by state
acs_merged <- acs_merged %>%
    left_join(select(LE, state, var1, var2), by = "state")

acs_merged <- acs_merged %>%
    left_join(select(MC, state, var1, var2), by = "state")

acs_merged <- acs_merged %>%
    left_join(select(CW, state, var1, var2), by = "state")

# glimpsing the dataset
glimpse(acs_merged)

```

## Preliminary plots

```{r}


```

```{r}

```

